web/router.ex
defmodule LifehopeAttendance.Router do
  use LifehopeAttendance.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
  end

  # Add this block
  scope "/", LifehopeAttendance do
    pipe_through :browser
    coherence_routes

    get "/", EventOccurrenceController, :index
  end

  # Add this block
  scope "/", LifehopeAttendance do
    pipe_through :protected
    coherence_routes :protected

    resources "/members", MemberController
    resources "/events", EventController
    resources "/event_occurrences", EventOccurrenceController do
      resources "/attendance", EventAttendanceController
      put "/attendance", EventAttendanceController, :visitor

    end
    resources "/attendances", AttendanceController
    resources "/record_attendances", RecordAttendanceController

    resources "/invitations", Coherence.InvitationController
    resources "/users", UserController
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  #
  # scope "/", LifehopeAttendance do
  #   pipe_through :browser # Use the default browser stack
  #
  #   get "/", EventOccurrenceController, :index
  #   resources "/members", MemberController
  #   resources "/events", EventController
  #   resources "/event_occurrences", EventOccurrenceController do
  #     resources "/attendance", EventAttendanceController
  #     put "/attendance", EventAttendanceController, :visitor
  #
  #   end
  #   resources "/attendances", AttendanceController
  #   resources "/record_attendances", RecordAttendanceController
  # end

  # Other scopes may use custom stacks.
  # scope "/api", LifehopeAttendance do
  #   pipe_through :api
  # end
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use LifehopeAttendance.Coherence.Web, :view


end

web/views/layout_view.ex
defmodule LifehopeAttendance.LayoutView do
  use LifehopeAttendance.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Life Hope Attendance Tracker</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div id="main"></div>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><%= link "Members", to: member_path(@conn, :index) %></li>
            <li><%= link "Event Types", to: event_path(@conn, :index) %></li>
            <!-- <li><%= link "Daily Attendance", to: event_occurrence_path(@conn, :index), class: "btn btn-success" %></li> -->
          </ul>
        </nav>
        <%= link "Attendance Tracker", to: event_occurrence_path(@conn, :index), class: "logo" %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>